### ISSUE TITLE
Add better <kbd> element styles for keyboard shortcut hints

### ISSUE THREAD

**Issue by ZMYaro** [ZMYaro/paintz#161]
Something like...
```css
kbd {
	display: inline-block;
	padding: 2px 8px;
	margin: -2px 4px;
	border-radius: 2px;
	background-color: rgba(128, 128, 128, 0.25);
	font: inherit;
	font-weight: bold;
}
```
